name: Release build

# on:
#   push:
#     tags:
#       - "v*"

on:
  push:
    branches:
      - build-cln-plugin

env:
  LSPD_GO_VERSION: 1.21.0

jobs:
  lspd:
    name: Release lspd
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, darwin]
        arch: [arm64, amd64]
    container:
      image: debian:bullseye-slim
    steps:
      - name: git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y make

      - name: setup go ${{ env.LSPD_GO_VERSION }}
        uses: actions/setup-go@v5
        with:
          go-version: "${{ env.LSPD_GO_VERSION }}"

      - name: build lspd
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: make release-all

      - name: zip lspd artifacts
        run: tar -czvf lspd-test-${{ matrix.os }}-${{ matrix.arch }}.tar.gz lspd lspd_cln_plugin

      - name: upload lspd artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lspd-test-${{ matrix.os }}-${{ matrix.arch }}
          path: lspd-test-${{ matrix.os }}-${{ matrix.arch }}.tar.gz

  release:
    needs:
      - lspd
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "**/*.gz"
          generateReleaseNotes: true
          draft: true
